### ISSUE TITLE
I can't search transaction and wallet using API

### ISSUE THREAD

**Issue by BlueeeStar** [donutAnees/Bitcoin-Investigation-Tool#1]

**Comment by donutAnees** [comment]
Hi, appreciate that you like my project!
Firstly, I noticed that you have used a blockhash for the transaction graph, which is the reason why the program throws error.  Rather run it using any Transaction Hash, it will generate a graph for you.

As for the wallet checker, you see the expected output, if the wallet is found on the websites you have specified in the `backend/tool_webscrapper/links.txt` file, then it will display it else it will display `wallet not found`.

Let me know if this works, more than happy to help if you run into any other issues. 

Thanks

**Comment by donutAnees** [comment]
Thanks so much for the feedback! I’m excited to get started on that.

**Comment by BlueeeStar** [comment]
Telegram, is it possible to get your address? We can have further consultations about the development of this project

**Comment by donutAnees** [comment]
Certainly, its @TheChosenDonut

**Comment by BlueeeStar** [comment]
I want to know which cryptocurrency addresses belong to whom. 

Thank you.
